version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_desafio
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_desafio
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always

volumes:
  mysql_data:
    driver: local
